### ISSUE TITLE
Is this still maintained ?

### ISSUE THREAD

**Issue by leonardo2204** [logicalzero/gamby#6]
I'm planning to buy a DIY module but I saw that the last commit in this repo was from 10/14/15.
My question is, is this still maintained ?

**Comment by logicalzero** [comment]
I plan on supporting the library indefinitely. There's been little movement only because the master branch is stable, and there are no outstanding issues nor pull requests. I have a few odds and ends in a local branch I intend to merge at some point, but nothing really important. 

On November 28, 2016 6:40:13 PM EST, Leonardo Ferrari <notifications@github.com> wrote:
>I'm planning to buy a DIY module but I saw that the last commit in this
>repo was from 10/14/15.
>My question is, is this still maintained ?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/logicalzero/gamby/issues/6

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by leonardo2204** [comment]
Thanks for the quick feedback ! 
And I`m glad to know that the lib is still alive !
Hope in the future I can contribute as well !
Thank you
