### ISSUE TITLE
Set Frame rate by code ?

### ISSUE THREAD

**Issue by leonardo2204** [logicalzero/gamby#7]
Hey @logicalzero, I was wondering if a setFrameRate function would be a good option to the lib.
I've started [porting rund.ino](https://github.com/leonardo2204/gamby_dino/), a dino chrome game that was written to arduboy.
The problem is, I'm not sure how to handle the "FPS" part of the game.
The solution I came up with (which sucks btw) is:

```C
void loop() {
  if (playing) {

    if (millis() > timeToDraw) {
    .... do all the coding stuff
     timeToDraw = millis() + gameSpeed;
     }
```

Is there a better approach to that ?

Thanks

**Comment by logicalzero** [comment]
Your approach is perfectly valid and a reasonable way to handle things. Frame rate is not really applicable; it’s mainly an artifact of display systems that continuously update. GAMBY updates only occur when explicitly called by the sketch, and only the portions of the screen that need updating are changed. In any case, generally speaking, game logic should generally not be tied to frame rate, since the rate can vary — especially on a slow microcontroller like that in an Arduino. Game timing should be based on the clock.

**Comment by leonardo2204** [comment]
Ok, so I'll keep this up.
Thanks for the tips !
